version: "3.8"
services:
  postgres:
    image: postgres:15
    volumes:
      - .postgres/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: tasted
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: tastebuds
